mathjax_plugin:
  enable_mathjax_plugin:
    client: true
    default: false
  mathjax_url:
    client: true
    default: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js
  mathjax_config:
    client: true
    default: TeX-AMS-MML_HTMLorMML
